export const ADD_ITEM = "add_item"
export const INPUT_VALUE = "input_value"
export const DELETE_ITEM = "delete_item"
export const SET_SELECT_ITEM = "set_select_item"
export const SET_ALL_SELECT = "set_all_select"
